# Generated by Django 5.2.8 on 2025-12-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_reset_token_created_at_alter_user_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_exercises',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
